CREATE TABLE IF NOT EXISTS alunos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(120),
    nickname VARCHAR(80),
    avatar TEXT,
    sexo CHAR(1),
    nascimento DATE,
    escola VARCHAR(120),
    ano SMALLINT,
    turma VARCHAR(20),
    partidas_pve INT NOT NULL DEFAULT 0,
    partidas_pvp INT NOT NULL DEFAULT 0,
    vitorias_pve INT NOT NULL DEFAULT 0,
    vitorias_pvp INT NOT NULL DEFAULT 0,
    questoes INT NOT NULL DEFAULT 0,
    acertos INT NOT NULL DEFAULT 0,
    pontos INT NOT NULL DEFAULT 0,
    progresso DECIMAL(5,2) NOT NULL DEFAULT 0,
    device VARCHAR(120),
    ticket VARCHAR(120),
    validade DATETIME,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY matricula_unique_idx (matricula)
);
